view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 500 # 需要登录的文章，未登录时可试看字数
    zsxqArticleReadCount: 300 # 星球专享文章/专栏，未解锁时可试看字数
    needPayArticleReadCount: 300 # 付费文章，未支付时可试看字数
    websiteName: 技术派
    websiteLogoUrl: https://paicoding.com/img/icon.png
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    paiChatName: 派聊聊
    paiSmartName: 派聪明
    paiSmartUrl: ${PAI_SMART_URL:http://localhost:9527/}
    zsxqUrl: https://paicoding.com/article/detail/314
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeTitle: 联系我 - 沉默王二的狗腿子
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png  # 这里是用于登录的普通公众号的二维码
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案被小人偷袭了
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到技术派，戳<a href="/article/detail/15">技术派全方位视角解读</a>了解我们
    columnInfoNews: 🎉 欢迎来到技术派教程频道！这里汇集了优质的技术专栏内容，助你快速成长！
    oss:
