# fixme 替换成目标小程序信息
wx:
  pay:
    # true 表示开启微信支付
    enable: ${WX_PAY_ENABLE:false}
    #应用id（小程序id）
    appId: ${WX_PAY_APP_ID:ww1****3e3}
    #商户号
    merchantId: ${WX_PAY_MERCHANT_ID:162****72}
    #商户API私钥
    privateKey: ${WX_PAY_PRIVATE_KEY:cert/apiclient_key.pem}
    #商户证书序列号
    # openssl x509 -in apiclient_cert.pem -noout -serial
    merchantSerialNumber: ${WX_PAY_MERCHANT_SERIAL_NUMBER:228065B**********F17C37A}
    #商户APIv3密钥
    apiV3Key: ${WX_PAY_API_V3_KEY:Pai******1}
    #支付通知地址
    payNotifyUrl: https://paicoding.com/wx/payNotify
    #退款通知地址
    refundNotifyUrl: https://paicoding.com/wx/refundNotify