view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    needPayArticleReadCount: 20 # 付费文章，未付费可以看到的文章内容
    websiteName: 技术派
    websiteLogoUrl: https://paicoding.com/img/logo.svg
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    contactMeTitle: 联系我 - 沉默王二的狗腿子
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案被小人偷袭了
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: https://paicoding.com
    welcomeInfo: 欢迎来到技术派，戳 <a href="/article/detail/155">技术派社区上线！</a> 了解我们
    zsxqUrl: https://paicoding.com/article/detail/314
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    oss: https://cdn.tobebetterjavaer.com/paicoding/static

knife4j:
  production: true # 开启屏蔽文档资源