paicoding:
  login:
    zsxq:
      api: https://wx.zsxq.com/connector/crm/identify_member.html
      appId: ${ZSXQ_APP_ID:2xxxx4}
      groupNumber: ${ZSXQ_GROUP_NUMBER:27xxxx38}
      secret: ${ZSXQ_SECRET:1b847xxxxxxb6260}
      redirectUrl: ${ZSXQ_REDIRECT_URL:https://paicoding.com/login/zsxq/callback}
    wx:
      loginQrType: ${WX_LOGIN_QR_TYPE:SERVICE_ACCOUNT} # SUBSCRIPTION_ACCOUNT 表示普通的公众号登录  SERVICE_ACCOUNT 表示服务号关注登录
      appId: ${WX_APP_ID:wx5xxxxb8}
      appSecret: ${WX_APP_SECRET:a7cxxxxxc84}
      qrCodeImg: ${view.site.contactMeWxQrCode}
      qrCodeLogo: ${view.site.websiteLogoUrl}
      securityCheckToken: ${WX_SECURITY_CHECK_TOKEN:} # 为空，表示不对微信回调的接口进行校验