# fixme 替换成目标小程序信息
wx:
  pay:
    # true 表示开启微信支付
    enable: false
    #应用id（小程序id）
    appId: ww17----a3e3
    #商户号
    merchantId: 16200072
    #商户API私钥
    privateKey: cert/apiclient_key.pem
    #商户证书序列号
    # openssl x509 -in apiclient_cert.pem -noout -serial
    merchantSerialNumber: 228065B42A411234A84FF0EF17C37A
    #商户APIv3密钥
    apiV3Key: Paixxdafsadfasdi1
    #支付通知地址
    payNotifyUrl: https://paicoding.com/wx/payNotify
    #退款通知地址
    refundNotifyUrl: https://paicoding.com/wx/refundNotify

